LEVEL         = 2
RECIPE        = kq3
GAME_SUBDIR   = kingsquest3
OBJS_SUBDIR   = objs_lsl
GAME_DIR_NAME = KQ3
SUPPORTFILES  = logDir object picDir sndDir viewDir \
                vol.0 vol.1 vol.2 vol.3 vol.4 vol.5 \
                vol.6 vol.7 vol.8 vol.9 vol.11 vol.12 vol.14 \
                words.tok

include ../sierra.mak
