# inetd configuration file format:
# ListenPort <server opts>,Process,Params,PathOpts
# valid server options are: telnet auth protect banner 
%TELNET_PORT% telnet protect banner,login,,eko=1 alf=1
%HTTPD_PORT%,httpd,
