#! /usr/bin/env python3

import io
import re
import sys

opcodesWithoutOperands = [
    'abx',
    'asla', 'aslb', 'asld', 'aslq',
    'asra', 'asrb', 'asrd', 'asrq',
    'break',
    'clra', 'clrb', 'clrd', 'comd', 'clre', 'clrf', 'clrw', 'clrq',
    'coma', 'comb', 'comd', 'come', 'comf', 'comw', 'comq',
    'daa',
    'deca', 'decb', 'dece', 'decf', 'decw', 'sync',
    'inca', 'incb', 'incd', 'ince', 'incf', 'incw',
    'log',
    'lsla', 'lslb', 'lsld', 'lsle', 'lslf', 'lslq',
    'lsra', 'lsrb', 'lsrd', 'lsre', 'lsrf', 'lsrq',
    'mul',
    'nega', 'negb', 'negd', 'nege', 'negf', 'negw', 'negq',
    'rti', 'rts',
    'rola', 'rolb', 'rold', 'rolw',
    'rora', 'rorb', 'rord', 'rorw',
    'sex', 'sexw', 'swi', 'swi2', 'swi3',
    'tsta', 'tstb', 'tstd', 'tste', 'tstf', 'tstw', 'tstq',
    # psedu-ops
    'ifp1', 'else', 'endc', 'ends', 'endm', 'endsect'
]

pseudoOpcodes = ['ifp1', 'ifgt', 'iflt', 'ifge', 'ifle', 'ifeq', 'ifne',
    'ifdef', 'else', 'endc', 'macro', 'endm', 'struct', 'ends'
]

opcodesWithFullLines = [
    'ttl'
]

opcodesWithStrings = [
    'fcc', 'fcs', 'fcn', 'fcz'
]

alphanumericCharset = '$0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'

def isEmptyLine(l):
    l.strip()
    if len(l) == 0:
        return True
    return False

def isComment(l):
    l.strip()
    if len(l) and (l[0] == '*' or l[0] == ';'):
        return True
    return False

def hasLabel(l):
    if len(l) > 0 and not l[0].isspace():
        return True
    return False

def buildStringOperand(l, op):
    dchar = ''
    sstr = ''
    idx = l.index(op) # skip to the start of the operand
#    sys.stderr.write('starting operand: "' + str(op) + "\"\n")

# lwasm version
    if idx < len(l) and not l[idx].isspace():
        dchar = l[idx] # get first delimiting char
        # we're assuming there's a matching delimiter
        end = idx + l[idx+1:].index(dchar) + 2

        # if there's a trailing comma, we add the comma to the operand and loop
        if end < len(l) and l[end] == ',':
            end += 1
            while end < len(l) and not l[end].isspace():
                end += 1

        sstr = l[idx:end]

    return sstr

def showLine(label, opcode, operand, comment, debug):
    if debug == True:
        line = [label, opcode, operand, comment]
        sys.stderr.write(str(line) + "\n")
#        print (line)
#        return

    if label == "" and opcode == "" and operand == "":
        line = comment
    else:
        if opcode.lower() in opcodesWithoutOperands:
            instr = opcode
        else:
            instr = opcode + ' ' + operand
        line = label + ' ' + instr + ' ' + comment

    line = line.rstrip()
    print(line)

def processLine(l):
    label = ""
    opcode = ""
    operand = ""
    comment = ""

    l = l.rstrip('\n')
    if isComment(l) == True:
        comment = l
    else:
        tokens = l.split()
        startIndex = 0
        if hasLabel(l) == True:
            # the next token will be a label
            label = tokens[startIndex]
            startIndex = startIndex + 1
        # the first token will be the opcode
        if len(tokens) > startIndex:
            opcode = tokens[startIndex]

            # if there's a second token AND the first token takes an operand, the second token is an operand
            if len(tokens) > startIndex + 1 and opcode.lower() not in opcodesWithoutOperands:
                operand = tokens[startIndex + 1]
                if len(tokens) > startIndex + 2:
                    if opcode.lower() in opcodesWithStrings:
                        operand = buildStringOperand(l, operand)

                        comment = l[(l.index(operand)+len(operand)):].strip()
                    elif opcode.lower() in opcodesWithFullLines:
                        operand = l.split(None, startIndex + 1)[startIndex + 1]
                    else:
                        comment = l.split(None, startIndex + 2)[startIndex + 2]
                else:
                    comment = ""
            else:
                if len(tokens) > startIndex + 1:
                    comment = l.split(None, startIndex + 1)[startIndex + 1]

    showLine(label, opcode, operand, comment, False)

sys.stdin.reconfigure(encoding='cp850')
sys.stdout.reconfigure(encoding='cp850')

for line in sys.stdin:
    processLine(line)
