#!/bin/sh
# Generate per-directory .gitignore files for NitrOS-9 build output.
#
# NitrOS-9 compiles modules directly into the source tree, so build artifacts
# sit next to their source. Each build directory's makefile already enumerates
# exactly what it produces in its `clean` target, so we ask make itself:
#
#     make -n clean MAKE=:
#
# `-n` prints the `rm -f ...` commands without deleting anything; `MAKE=:`
# turns the recursive `$(MAKE) -C subdir clean` lines into harmless no-ops so
# each directory reports only its OWN outputs (children generate their own
# .gitignore). The ignore list therefore tracks `make clean` exactly: only real
# build products are ignored, never source.
#
# Every entry is anchored with a leading '/' because `make clean` only removes
# files in its own directory -- this keeps a glob like '/*.a' from leaking into
# a subdirectory that holds tracked source (e.g. lib/kreiderclib/qsort.a).
#
# Tokens that reference a parent ('../foo') are redirected into that parent's
# .gitignore. The repo-root .gitignore is curated by hand and left untouched.
#
# Re-run from the repo root after makefiles change. Idempotent.
set -eu

cd "$(dirname "$0")/.."

MARKER='# AUTO-GENERATED by scripts/gen-gitignores.sh from `make clean` -- do not edit by hand'
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

# Map a target directory to a flat temp filename used to accumulate its tokens.
slug() { printf '%s' "$1" | tr '/.' '__'; }

find . -type f \( -name makefile -o -name Makefile \) -print | sed 's|/[^/]*$||' | sort -u | while read -r dir; do
    ( cd "$dir" && make -n clean MAKE=: 2>/dev/null ) \
        | grep -E '^[[:space:]]*rm -f' \
        | sed -E 's/^[[:space:]]*rm -f[[:space:]]*//' \
        | tr ' ' '\n' \
        | grep -v '^$' \
        | grep -vx 'clean' \
    | while read -r tok; do
        target=$dir
        # Resolve any leading ../ segments into the actual ancestor directory.
        while [ "${tok#../}" != "$tok" ]; do
            tok=${tok#../}
            target=$(dirname "$target")
        done
        # Skip anything that still escapes the tree or is the repo root itself.
        case "$tok" in */../*|*/..) continue;; esac
        [ "$target" = "." ] && continue   # root .gitignore is hand-curated
        printf '/%s\n' "$tok" >> "$WORK/$(slug "$target")"
        printf '%s\n' "$target" >> "$WORK/targets"
    done
done

[ -f "$WORK/targets" ] || { echo "no targets"; exit 0; }

count=0
sort -u "$WORK/targets" | while read -r target; do
    {
        printf '%s\n' "$MARKER"
        sort -u "$WORK/$(slug "$target")"
    } > "$target/.gitignore"
    count=$((count + 1))
done
echo "Wrote $(sort -u "$WORK/targets" | wc -l | tr -d ' ') .gitignore files."

# A few makefiles list committed files in their own clean target (e.g. a
# checked-in .dsk in the same dir). We must never let a GENERATED pattern shadow
# a tracked file, so re-include any such file with a negation. We only touch
# files we generated (identified by the marker); tracked files that are shadowed
# only by the hand-curated root .gitignore globs (*.dsk, *.list, ...) are left
# exactly as the maintainers committed them.
git ls-files -i -c --exclude-standard | while read -r f; do
    gi="$(dirname "$f")/.gitignore"
    if [ -f "$gi" ] && head -1 "$gi" | grep -qF "$MARKER"; then
        printf '!/%s\n' "$(basename "$f")" >> "$gi"
    fi
done
